### ISSUE TITLE
Vercel not run

### ISSUE THREAD

**Issue by almaziphone** [bot-base/telegram-bot-template#594]
ReferenceError: convertKeysToCamelCase is not defined
    at <anonymous> (/vercel/path0/api/index.ts:9:16)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async d (/opt/rust/nodejs.js:8:16871)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue

**Comment by almaziphone** [comment]
Вы изменили logger.ts, убрав createLogger. Исправьте /api/index.ts

**Comment by semklim** [comment]
Hi @almaziphone, I fixed the deployment issue on Vercel. Please check my pull request #614.
